- name: /etc/shells check
  shell: " cat /etc/shells | grep /usr/local/bin/zsh && echo 'found' || echo ''"
  register: shells_writed
- name: zsh 設定
  shell: |
    sudo sh -c "sudo echo /usr/local/bin/zsh >> /etc/shells"
    chsh -s /usr/local/bin/zsh
  when: (not shells_writed.stdout)

- name: .zsh.global check
  shell: " cat .zshrc | grep .zsh.global && echo 'found' || echo ''"
  register: zshglobal_exist
- name: add zshrc.global
  shell: echo source ~/.zsh.global >> ~/.zshrc
  when: (not zshglobal_exist.stdout)
- name: add zshrc.global to zshrc
  file: src={{ pwd }}/dotfiles/zsh/.zsh.global dest=~/.zsh.global force=yes state=link
  when: (not zshglobal_exist.stdout)
